const { SlashCommandBuilder } = require('discord.js');

const facts = [
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old and still edible.",
  "Octopuses have three hearts.",
  "Bananas are berries, but strawberries are not.",
  "The Eiffel Tower can be 15 cm taller during the summer due to heat expansion.",
  "Sharks have been around longer than trees.",
  "Wombat poop is cube-shaped.",
  "A day on Venus is longer than a year on Venus.",
  "The heart of a blue whale is as big as a small car.",
  "Sloths can hold their breath longer than dolphins.",
  "Oxford University is older than the Aztec Empire.",
  "A single strand of spaghetti is called a 'spaghetto'.",
  "There are more stars in the universe than grains of sand on Earth.",
  "Humans share about 60% of their DNA with bananas.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The majority of your brain is fat.",
  "The wood frog can survive being frozen for weeks.",
  "Cows have best friends and can become stressed when separated.",
  "Scotland's national animal is the unicorn.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "Mosquitoes are attracted to people who just ate bananas.",
  "Hot water can freeze faster than cold water, known as the Mpemba effect.",
  "Sea otters hold hands when they sleep so they don't drift apart.",
  "Butterflies can taste with their feet.",
  "The Twitter bird’s name is Larry.",
  "Tigers have striped skin, not just striped fur.",
  "Koalas have fingerprints almost identical to humans.",
  "Pineapples take about 2 years to grow.",
  "The total weight of ants on Earth roughly equals the total weight of humans.",
  "Your fingernails grow faster on your dominant hand.",
  "Some turtles can breathe through their butts.",
  "Humans are the only animals that blush.",
  "A cloud can weigh more than a million pounds.",
  "The average person walks the equivalent of 5 times around the world in their lifetime.",
  "You can’t hum while holding your nose.",
  "There’s enough DNA in the human body to stretch from the sun to Pluto and back — 17 times.",
  "Goosebumps are a reflex from when humans had more body hair.",
  "Snails can sleep for up to 3 years.",
  "A group of flamingos is called a 'flamboyance'.",
  "Some cats are allergic to humans.",
  "There’s a species of jellyfish that can live forever (biologically immortal).",
  "The moon has moonquakes.",
  "Tomatoes have more genes than humans.",
  "An octopus can taste with its arms.",
  "A single sneeze travels at about 100 mph.",
  "The average cumulus cloud contains about 500,000 kilograms of water.",
  "Humans glow in the dark — just not bright enough to see.",
  "You are about 1 cm taller in the morning than at night.",
  "Alaska is the westernmost, easternmost, and northernmost state in the U.S.",
  "Rabbits can’t vomit.",
  "Banging your head against a wall for one hour burns 150 calories. (Not recommended.)",
  "There are more fake flamingos in the world than real ones.",
  "The inventor of the microwave appliance only received $2 for his discovery.",
  "The smell of freshly-cut grass is actually a plant distress call.",
  "A baby puffin is called a 'puffling'.",
  "Spaghettification is a real term in astrophysics — it describes what happens if you fall into a black hole.",
  "Some lobsters taste with their feet.",
  "The longest hiccuping spree lasted 68 years.",
  "Antarctica is the driest, windiest, and coldest continent — and also a desert.",
  "Humans are bioluminescent, but the light is too weak for our eyes.",
  "An apple, potato, and onion all taste the same if you plug your nose.",
];

module.exports = {
  data: new SlashCommandBuilder()
    .setName('fact')
    .setDescription('Get a random fun fact'),
  async execute(interaction) {
    const fact = facts[Math.floor(Math.random() * facts.length)];
    await interaction.reply(fact);
  },
};
